### PR TITLE
Echo original_spec_nvr earlier

### PR DESCRIPTION
**Pull request by johnbieren**
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

### CODE REVIEW

**Comment by pypingou** [comment]
👍 for me, thanks :)


(If we had kept the ticket open we could have close it w/ this commit (and thus link both also on GH's UI)).

**Comment by arilivigni** [comment]
@pypingou added it you don't have to reopen to comment and this just decreases the window still not 100% guaranteed

**Comment by johnbieren** [comment]
[merge]

**Comment by pypingou** [comment]
> this just decreases the window still not 100% guaranteed

Indeed, and it's where the re-trigger mechanism becomes crucial :)

**Pull request merged**
