### PR TITLE
add repository with latest packages build in koji.

### PR DESCRIPTION
**Pull request by bgoncalv**
The repo has lower priority, this should avoid errors trying to install packages that are not in official repos.

Also enable updates-testing repo if it is not in Rawhide.

### CODE REVIEW

**Comment by bgoncalv** [comment]
More info about latest fedora repos: https://fedoraproject.org/wiki/Repositories

**Comment by thrix** [comment]
the problem here is, that the same packages will be always prioritized from the production repos. Only packages not found in the production repos will be installed from here. So I do not thing this makes sense.

What we need is what I tried to do on downstream:
Identify which koji builds we need to add to production repos, to be able to install the koji build. Then add those package with the same priority (or even higher priority - note means lower number priority in yum conf), so they are actually installed.

**Comment by thrix** [comment]
Ok, I tested, and this works nicely also. No need to do magic scripting :) let's bring this in.

**Comment by thrix** [comment]
@johnbieren this is good to go :) are you ok also?

**Comment by thrix** [comment]
> the problem here is, that the same packages will be always prioritized from the production repos. Only packages not found in the production repos will be installed from here. So I do not think this makes sense.
> 
> What we need is what I tried to do on downstream:
> Identify which koji builds we need to add to production repos, to be able to install the koji build. Then add those package with the same priority (or even higher priority - note means lower number priority in yum conf), so they are actually installed.

scratch this, this is not true. the packages are chosen only from valid candidates really.

**Comment by johnbieren** [comment]
@thrix yeah, looks fine to me. Feel free to merge

**Comment by bgoncalv** [comment]
[upstream-merge]

**Pull request merged**
