### PR TITLE
make sure fedora rawhide has GPG key imported

### PR DESCRIPTION
**Pull request by bgoncalv**
attempt to solve issues like: https://jenkins-continuous-infra.apps.ci.centos.org/view/Fedora%20All%20Packages%20Pipeline/job/fedora-rawhide-build-pipeline/2165/artifact/package-tests/logs/FAIL_str_rust-cargo-test.log

### CODE REVIEW

**Comment by bgoncalv** [comment]
It seems there is some issue with stage environment.

Anyway, it seems to work on prod: https://jenkins-continuous-infra.apps.ci.centos.org/view/Fedora%20All%20Packages%20Pipeline/job/fedora-rawhide-build-pipeline/2173/


@johnbieren @joejstuart what do you think? Should this be done at the image test for Rawhide instead, if so I'm not really sure how to do it :)

**Comment by johnbieren** [comment]
It seems it may be able to go https://github.com/CentOS-PaaS-SIG/upstream-fedora-pipeline/blob/master/vars/fedoraImageTest.groovy#L22 in the testCompose function, but I am not even sure where testCompose is defined. I am fine with you putting the change where you have it here.

**Comment by johnbieren** [comment]
Stage is messed up because it is having trouble publishing on fedmsg stage. I'll check it out

**Comment by johnbieren** [comment]
[upstream-test] [test]

**Comment by johnbieren** [comment]
Seems to be fine. The atomic stage job failed the mockbuild it seems, but the all packages stage job finished unstable, which I think it typically does

**Comment by bgoncalv** [comment]
[upstream-merge]

**Pull request merged**
