### PR TITLE
Add description to the shell scripts

### PR DESCRIPTION
**Pull request by Turivniy**

### CODE REVIEW

**Comment by Turivniy** [comment]
It will update steps with the description in the Blue Ocean stages.
All of the "Shall Script" steps will be updated with the description.

**Comment by johnbieren** [comment]
@bgoncalv wdyt? It lgtm

**Comment by bgoncalv** [comment]
@johnbieren it lgtm, I just don't know how many of this function we are actually using :)
Like some moved to contra-lib other to upstream-first repo....

https://github.com/openshift/contra-lib/blob/master/src/org/centos/contra/pipeline/Utils.groovy

https://github.com/CentOS-PaaS-SIG/upstream-fedora-pipeline/blob/master/src/org/centos/pipeline/PackagePipelineUtils.groovy

**Comment by johnbieren** [comment]
Agreed, but might as well [merge] I suppose

**Pull request merged**
