### PR TITLE
UPDATE task for ci-pipeline-ostree-image-boot-sanity

### PR DESCRIPTION
**Pull request by robnester-rh**
Updated task value for ci-pipeline-ostree-image-boot-sanity as it was
pointing to an incorrect value after the jenkinsfile refactor in August.
Mea culpa.

### CODE REVIEW

**Comment by p3ck** [comment]
I believe this change should be added as well
`[bpeck@bpeck ci-pipeline]$ git diff
diff --git a/src/org/centos/pipeline/PipelineUtils.groovy b/src/org/centos/pipeline/PipelineUtils.groovy
index 35d45c0..badc53c 100644
--- a/src/org/centos/pipeline/PipelineUtils.groovy
+++ b/src/org/centos/pipeline/PipelineUtils.groovy
@@ -550,11 +550,12 @@ def rsyncData(String stage){
 
     } else if (stage == 'ci-pipeline-ostree-image-boot-sanity') {
         text = text +
+                "export image2boot=\"${env.image2boot}\"\n" +
+                "export commit=\"${env.commit}\"\n" +
                 "export ANSIBLE_HOST_KEY_CHECKING=\"False\"\n"
     } else if (stage == 'ci-pipeline-ostree-boot-sanity') {
         text = text +
                 "export fed_repo=\"${env.fed_repo}\"\n" +
-                "export image2boot=\"${env.image2boot}\"\n" +
                 "export commit=\"${env.commit}\"\n" +
                 "export ANSIBLE_HOST_KEY_CHECKING=\"False\"\n"
     } else if (stage == 'ci-pipeline-functional-tests') {
`

**Comment by p3ck** [comment]
https://paste.fedoraproject.org/paste/U4NdP6RajxoAVL6KzVgoLQ

**Comment by robnester-rh** [comment]
@p3ck - I've added the suggestions you provided and pushed another commit to this PR. Please let me know if you approve.

**Comment by p3ck** [comment]
[test]

**Comment by robnester-rh** [comment]
[merge]

**Pull request merged**
