### PR TITLE
UPDATE setMessageFields() to use HashMap

### PR DESCRIPTION
**Pull request by robnester-rh**
Updated setMessageFields() to use build a HashMap instead of a string
when creating the messageProperties. This allows for overwriting of
values instead of having to set them on a message type basis.

### CODE REVIEW

**Comment by robnester-rh** [comment]
[test]

**Comment by scoheb** [comment]
[test] letting Bill's PR go first

**Comment by robnester-rh** [comment]
[test]

**Comment by robnester-rh** [comment]
[test]

**Comment by robnester-rh** [comment]
[merge]

**Pull request merged**
