### PR TITLE
Ensure container templates present before builds

### PR DESCRIPTION
**Pull request by scoheb**
- create-containers.sh no longer fails if resource already exists
- JenkinsfileStageTrigger now calls create-containers.sh

### CODE REVIEW

**Comment by arilivigni** [comment]
If I am writing the playbooks why do we need this?  Can't we just call a roll to create containers?

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
I misunderstood our IRC chat...I thought you were going to be calling this script from a playbook...

**Comment by arilivigni** [comment]
wrote back on IRC.  Sorry I thought it was clear of course you have a lot more logic in the shell script now.  Is all this necessary?

**Comment by scoheb** [comment]
[merge]

**Pull request merged**
