### PR TITLE
Watch stage messages

### PR DESCRIPTION
**Pull request by scoheb**

### CODE REVIEW

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by p3ck** [comment]
[test] dreaded -1

**Comment by p3ck** [comment]
[test] stupid -1 again

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[merge]

**Pull request merged**
