### PR TITLE
Fedora upstream will support PRs on tests namespace

### PR DESCRIPTION
**Pull request by bgoncalv**
For Fedora upstream pipeline to support PR on tests namespace these changes are required

Some trailing whitespaces got removed as well.

### CODE REVIEW

**Comment by bgoncalv** [comment]
[upstream-test]

**Comment by bgoncalv** [comment]
@johnbieren does this make sense? :)

**Comment by johnbieren** [comment]
So if namespace = tests, the dir where the tests live is just different? That makes sense to me. Won't triggers have to change to listen to the additional namespace as well?

**Comment by bgoncalv** [comment]
> So if namespace = tests, the dir where the tests live is just different? That makes sense to me. 
Yes, the idea if tests.yml will be defined directly on root of the repo, like https://src.fedoraproject.org/tests/shell/tree/master there there would be tests.yml there. @psss is it correct?

>Won't triggers have to change to listen to the additional namespace as well?
Yes, on `upstream-fedora-pipeline` we will need to include new trigger for it, also some other changes to the main Jenkinsfile to handle it, and I believe some changes related to the message sent to fedmsg. But I haven't had time to check it into details yet.

**Comment by psss** [comment]
> Yes, the idea if tests.yml will be defined directly on root of the repo, like https://src.fedoraproject.org/tests/shell/tree/master there there would be tests.yml there. @psss is it correct?

Yes, exactly. The `tests.yml` file should be in the root of the test namespace directory so that tests then can be referenced from it directly.

**Comment by bgoncalv** [comment]
[upstream-merge] [merge]

**Comment by bgoncalv** [comment]
@johnbieren fyi, singlehost-test image didn't get promoted automatically, we needed to tag it manually.

**Comment by johnbieren** [comment]
@bgoncalv yeah, the upstream-merge and merge trigger two separate merge jobs. One promotes cloud-image-compose, the other promotes singlehost-test (among others). No good answer is in place for PRs that affect both. I know you commented both merge commands (wisely), but it seems that whichever merge job goes first actually merges the PR and continues and the other does nothing I guess

**Pull request merged**
