### PR TITLE
Install python2-dnf when necessary

### PR DESCRIPTION
**Pull request by johnbieren**
I see some failures for python2-dnf not being present on the qcow2 image, which makes the dnf module not work

### CODE REVIEW

**Comment by dirgim** [comment]
Hmm, does it fail in the playbook on the "Check which rpms are installed" task or somewhere else?

**Comment by johnbieren** [comment]
Yes, check which rpms are installed.
msg": "`python2-dnf` is not installed, but it is requiredfor the Ansible dnf module.

**Comment by dirgim** [comment]
Then I think only shell installation will work there, as package will also fail on that task.

**Comment by johnbieren** [comment]
Good point, I'll fix it

**Comment by johnbieren** [comment]
[merge]

**Pull request merged**
