### PR TITLE
Change f to fc in original_spec_nvr

### PR DESCRIPTION
**Pull request by johnbieren**
I expect this to resolve https://github.com/CentOS-PaaS-SIG/ci-pipeline/issues/399
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

### CODE REVIEW

**Comment by johnbieren** [comment]
[test]

**Comment by pypingou** [comment]
👍 for me and thanks :)

**Comment by johnbieren** [comment]
[test]

**Comment by johnbieren** [comment]
[test]

**Comment by johnbieren** [comment]
[test]

**Comment by johnbieren** [comment]
[test]

**Comment by johnbieren** [comment]
[test] fedpkg clone timed out

**Comment by johnbieren** [comment]
@pypingou Hey, this won't work if the branch is master (rawhide).  Do you have some way for me to get the numerical equivalent of master? I don't know of any way to check what release master currently corresponds to

**Comment by johnbieren** [comment]
@pypingou Is there any better solution than this?
for i in 1 2 3 4 5; do curl -s https://src.fedoraproject.org/rpms/fedora-release/raw/master/f/fedora-release.spec | awk '/%define dist_version/ { print $3}'; done

**Comment by pypingou** [comment]
The current best way is likely hitting pkgdb's API: https://admin.fedoraproject.org/pkgdb/api/collections?pattern=master

However, pkgdb is now on life support (and basically read-only). but while we're working on finding a replacement for it, it's going to stay there for a little longer.

Another place would be mdapi: https://apps.fedoraproject.org/mdapi/rawhide/pkg/fedora-release but that doesn't seem ideal either :(

I'm looking to see if there is something better than pkgdb already available somewhere.

**Comment by johnbieren** [comment]
[test]

**Comment by johnbieren** [comment]
@scoheb Is squashing a requirement or will this work as is?

**Comment by scoheb** [comment]
Not a requirement... just makes the got log easier to read...

**Comment by johnbieren** [comment]
[merge]

**Pull request merged**
