### PR TITLE
Only fail if datagrepper returns NOTFOUND

### PR DESCRIPTION
**Pull request by scoheb**
- this will reduce the number of failures due to datagrepper
  instabilities.

### CODE REVIEW

**Comment by scoheb** [comment]
[test] openshift API errors

**Comment by scoheb** [comment]
[test] HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://koji.fedoraproject.org/kojihub

**Comment by johnbieren** [comment]
[test] koji fixed yet?

**Comment by scoheb** [comment]
[test] koji fixed but there was a kubernetes plugin error...

**Comment by scoheb** [comment]
[merge] errors not related to change...

**Pull request merged**
