### PR TITLE
singlehost-test: install ansible 2.5

### PR DESCRIPTION
**Pull request by thrix**
As a workaround until STR works with 2.4 version.

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by johnbieren** [comment]
I'll log in when the stage job runs and make sure the proper ansible version exists. I'll report back

**Comment by johnbieren** [comment]
[upstream-test] randomly got a node without nested virt enabled, which was supposed to be fixed a few days ago..

**Comment by johnbieren** [comment]
[upstream-test] infra issues

**Comment by johnbieren** [comment]
This is what I get from a pod running with this change:

sh-4.2# ansible --version                                                                                                                                                                                                                 
 [WARNING] Ansible is being run in a world writable directory (/workDir), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
ansible 2.5.8                                                                                                                                                                                                                             
  config file = /etc/ansible/ansible.cfg                                                                                                                                                                                                  
  configured module search path = [u'/workDir/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']                                                                                                                           
  ansible python module location = /usr/lib/python2.7/site-packages/ansible                                                                                                                                                               
  executable location = /usr/bin/ansible                                                                                                                                                                                                  
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]                                                                                                                                         
sh-4.2# rpm -qa ansible                                                                                                                                                                                                                   
ansible-2.4.2.0-2.el7.noarch                                                                                                                                                                                                              
sh-4.2# yum info ansible                                                                                                                                                                                                                  
Loaded plugins: fastestmirror, ovl                                                                                                                                                                                                        
Loading mirror speeds from cached hostfile                                                                                                                                                                                                
 * base: mirror2.ci.centos.org                                                                                                                                                                                                            
 * epel: mirror.es.its.nyu.edu                                                                                                                                                                                                            
 * extras: mirror2.ci.centos.org                                                                                                                                                                                                          
 * updates: mirror2.ci.centos.org                                                                                                                                                                                                         
Installed Packages                                                                                                                                                                                                                        
Name        : ansible                                                                                                                                                                                                                     
Arch        : noarch                                                                                                                                                                                                                      
Version     : 2.4.2.0                                                                                                                                                                                                                     
Release     : 2.el7                                                                                                                                                                                                                       
Size        : 38 M                                                                                                                                                                                                                        
Repo        : installed                                                                                                                                                                                                                   
From repo   : extras                                                                                                                                                                                                                      
Summary     : SSH-based configuration management, deployment, and task execution system                                                                                                                                                   
URL         : http://ansible.com                                                                                                                                                                                                          
License     : GPLv3+                                                                                                                                                                                                                      
Description :                                                                                                                                                                                                                             
            : Ansible is a radically simple model-driven configuration management,                                                                                                                                                        
            : multi-node deployment, and remote task execution system. Ansible works                                                                                                                                                      
            : over SSH and does not require any software or daemons to be installed                                                                                                                                                       
            : on remote nodes. Extension modules can be written in any language and                                                                                                                                                       
            : are transferred to managed machines automatically.

**Comment by bgoncalv** [comment]
The patch works well.
The ansible rpm to be installed it is expected (even if it was not installed explicitly) as it is dependency of standard-test-roles.
pip install ansible 2.5.8 and overwrites ansible module. Not pretty, but works.

The only problem I see is the singlehost image does not contain the patch from PR710. @thrix could you rebase this PR?

**Comment by thrix** [comment]
@bgoncalv of course, rebasing now

**Comment by thrix** [comment]
@bgoncalv done ... Let's get this in so we can unblock the testing. I conclude with you, that is works, but is not nice. It's a workaround we will remove once unpleasant ansible 2.6+ bug is fixed or STR had 2.4 compatibility restored.

**Comment by bgoncalv** [comment]
[merge]

**Comment by johnbieren** [comment]
fwiw, the rebase wasn't too necessary unless it needed Bruno's patch to pass stage. Once this PR was merged (Bruno's was already), the image would have been rebuilt from master and tagged as stable

**Pull request merged**
