### PR TITLE
 Fixing image related messages

### PR DESCRIPTION
**Pull request by arilivigni**
- Type-o in PipelineUtils
- Added + after compose_url
- Updated README.md

### CODE REVIEW

**Comment by scoheb** [comment]
[test] weird jenkins pipeline error

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by scoheb** [comment]
[test]

**Comment by johnbieren** [comment]
[test] curl transfer unexpectedly closed

**Comment by johnbieren** [comment]
[test] fedpkg clone timed out again...

**Comment by scoheb** [comment]
[test] curl transfer unexpectedly closed

**Comment by arilivigni** [comment]
[test]

**Comment by arilivigni** [comment]
[merge]

**Pull request merged**
