### PR TITLE
disable GPG check for Rawhide

### PR DESCRIPTION
**Pull request by bgoncalv**
related to https://pagure.io/fedora-ci/general/issue/39

### CODE REVIEW

**Comment by bgoncalv** [comment]
[upstream-test]

**Comment by johnbieren** [comment]
If you rebase your PR so your pipelineUtils includes my new buildImage, testing should run for this normally

**Comment by bgoncalv** [comment]
@johnbieren it doesn't seem to work: https://jenkins-continuous-infra.apps.ci.centos.org/view/all/job/fedora-stage-ci-pipeline-trigger/353/console

**Comment by johnbieren** [comment]
[upstream-test]

**Comment by johnbieren** [comment]
[upstream-test] image was set to use cache

**Comment by johnbieren** [comment]
[upstream-test] image was set to use cache

**Comment by bgoncalv** [comment]
[upstream-merge]

**Pull request merged**
