### PR TITLE
Containerize ostree image compose

### PR DESCRIPTION
**Pull request by johnbieren**
Change the entire ostree image compose stage to run fully in OpenShift containers and use no duffy hosts.
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

### CODE REVIEW

**Comment by johnbieren** [comment]
Will have to rebase this before merging. @scoheb Can you push an initial stable image for this when you get a chance?

**Comment by johnbieren** [comment]
[test]

**Comment by johnbieren** [comment]
[test] this passed.. but jenkins rebooted at the end of the stage job so killed it..

**Comment by scoheb** [comment]
[test]

**Comment by johnbieren** [comment]
[merge] not sure why this still says pending https://jenkins-continuous-infra.apps.ci.centos.org/view/CI-Stage-Pipeline/job/ci-stage-pipeline-trigger/515/

**Pull request merged**
