### PR TITLE
use the github api

### PR DESCRIPTION
**Pull request by joejstuart**
Instead of parsing the html, use the github api.

### CODE REVIEW

**Comment by scoheb** [comment]
Will you port this to contra-env-setup?

**Comment by arilivigni** [comment]
@joejstuart you were going to add this back into the contra-lib correct?

**Comment by joejstuart** [comment]
@scoheb yes, Is there a reason for it to exist here even?
@arilivigni I'm not following. The contra-lib stuff is just shared libraries right now.

**Comment by arilivigni** [comment]
@joejstuart sorry I didn't look at was added.   I think I'm going to remove the dev_setup since folks get confused sometimes.   I saw your PR in the other repo will review

**Comment by arilivigni** [comment]
@joejstuart speaking of libraries can we add library setup and use in https://githib.com/CentOS-PaaS-SIG/contra-env-setup?

**Comment by joejstuart** [comment]
@arilivigni yes, good idea. I'll put a card in for it.

**Pull request closed without merging**
