### PR TITLE
apply PR patches to head of branch

### PR DESCRIPTION
**Pull request by bgoncalv**
Make sure to test PR against HEAD of the branch.

### CODE REVIEW

**Comment by bgoncalv** [comment]
[test]

**Comment by bgoncalv** [comment]
[test]

**Comment by johnbieren** [comment]
[test] pod log is gone

**Comment by johnbieren** [comment]
[upstream-test] whoops

**Comment by johnbieren** [comment]
[upstream-test] error syncing pod

**Comment by johnbieren** [comment]
[merge] failure due to rawhide qcow2 not working

**Pull request merged**
