### PR TITLE
sendMessageWithAudit: make optional to check message in datagrepper

### PR DESCRIPTION
**Pull request by bgoncalv**

### CODE REVIEW

**Comment by bgoncalv** [comment]
@johnbieren could you check this?

**Comment by bgoncalv** [comment]
The pipeline failed, but due to unrelated issue.

**Comment by johnbieren** [comment]
I don't like this change. If you don't want to track the message, sendMessage should be used instead. The only difference between sendMessage and sendMessageWithAudit is tracking the message

**Comment by bgoncalv** [comment]
hmm, okay. I can use sendMessage.

the sendMessageWithAudit also creates the audit file.

Feel free to close the PR

**Pull request closed without merging**
